### ISSUE TITLE
oauth for google linkedin fb

### ISSUE THREAD

**Issue by hubyhuby** [WolvesFortress/vxbl-oauth#1]
Would it be possible to provide other oauth provider like google linkedin ?
If think this is an important package to have, login is a very basic thing you need for vweb.

Then maybe to generalise the package to something like https://github.com/markbates/goth

**Comment by inxomnyaa** [comment]
No
- project is basically suspended due to me leaving vlang development
- xbl auth was intentionally chosen as xbox/M$ accounts are used in MCPE, i have no plans on adding other auth methods. vlang does not even support the necessary crypto things needed for modern oauth

**Comment by hubyhuby** [comment]
Thanks for your resume. It actually answers other questions I had. Such as how mature is Vlang for a backend developpement. 
I like a lot this language, will see in a year how it has evolved and if we have all the bells and whistles for a full fledge web app. Have fun.
